package com.example.s1891132.coinz

import org.junit.Test

import org.junit.Assert.*

class CurrentUrlKtTest {
    //test whether the current date and url generated by the function is correct
    //you need to modify the date and url of the day when you test in a different day

    @Test
    fun currentDateTest() {
        assertEquals("2018/12/07", currentDate())
    }

    @Test
    fun currentUrlTest() {
        assertEquals("http://homepages.inf.ed.ac.uk/stg/coinz/2018/12/07/coinzmap.geojson", currentUrl())
    }
}